services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: my-java-app-container
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-java-app-pipeline_java-network
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    container_name: my-db-container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-java-app-pipeline_java-network
networks:
  my-java-app-pipeline_java-network:
    external: true
