services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: my-java-app-container
    depends_on:
      - db
    networks:
      - java-network
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    container_name: my-db-container
    networks:
      - java-network
networks:
  java-network:
    driver: bridge
