services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: my-java-app-container
    networks:
      - java-network
networks:
  java-network:
    driver: bridge
